name: CI/CD Pipeline - Flask App

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t flask-deploy-demo .

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker stop flask-app || true
          docker rm flask-app || true
          docker pull flask-deploy-demo || true
          docker run -d --name flask-app -p 80:5000 flask-deploy-demo

